### ISSUE TITLE
baton-metaquery, "smallbin double linked list corrupted"

### ISSUE THREAD

**Issue by mcast** [wtsi-npg/baton#106]
While querying for what I thought would be ipwd,
```
$ jq -n '{collection:".",avus:[]}' | baton-metaquery --avu
2015-03-09T14:41:48 ERROR Failed to stat iRODS path '.': 1.
2015-03-09T14:41:48 ERROR Failed to stat iRODS path '.': 1.
2015-03-09T14:41:51 ERROR Failed to stat iRODS path '': 1.
2015-03-09T14:41:51 ERROR Failed to list metadata on '': error -310000 Path '' does not exist (or lacks access permission).
2015-03-09T14:41:51 ERROR Path '' does not exist (or lacks access permission).
2015-03-09T14:41:51 ERROR Path '' does not exist (or lacks access permission).
*** glibc detected *** baton-metaquery: malloc(): smallbin double linked list corrupted: 0x00000000013ad120 ***
[...wait...]
^C
$ jq -n '{collection:".",avus:[]}' | baton-metaquery | jq . | wc
2015-03-09T14:53:38 ERROR Failed to stat iRODS path '.': 1.
2015-03-09T14:53:38 ERROR Failed to stat iRODS path '.': 1.
  41068   61540 1297017
```
It seems to emit a list of *all files* so I didn't wait for completion with `--avu`.

This is with `/software/gapi/pkg/baton/0.13.0/bin/baton-metaquery` to irods-cgp-dev (3.3.1).  I don't need it fixed, I was just trying to save myself typing by using `./` and the report of linked list corruption made me think you might want to investigate.

**Comment by keithj** [comment]
Thanks. This is a bug. I'll take a look.

**Comment by keithj** [comment]
The ````collection```` property in a query is optional and may be used for two purposes; firstly, if it's just a zone e.g. ````/seq```` then it is used as a zone hint so that iRODS knows in which zone to run the query and secondly, if there is at least one collection in addition to the zone e.g. ````/seq/public```` then the path is used to restrict the metadata search results to items under that path. I've found that this can make the queries run slowly.

When you give the relative path ````.```` baton should resolve this to your current zone before doing anything, but it doesn't. That is the bug. If you omit the  ````collection```` property it will give you the expected result (i.e. query the current zone). If you want to run the query in another zone, use the ````/zone```` syntax.

**Comment by keithj** [comment]
Also note that it is unsafe to use any relative collection or data object path in either 3.3.1 or 4.x because of irods/irods#2406. I will add a couple of new features to help deal with this; a warning to be printed when relative paths are passed in and CLI flags to either silence the warning or upgrade the warning to an error which will cause the program to exit.

**Comment by mcast** [comment]
OK, that makes sense thanks - I'll avoid relative paths.

**Comment by keithj** [comment]
I''l leave this open until the fix is merged.

**Comment by keithj** [comment]
This is all in the latest pull request which is awaiting merging.
