### ISSUE TITLE
Enhancement Request: add support for with_durability

### ISSUE THREAD

**Issue by kript** [wtsi-npg/baton#228]
As sort of documented [here](https://github.com/irods/irods/issues/4976#issuecomment-646195118) 4.2.7 contains the `irods::with_durability` library which allows the kind of retries than can be done with `iput` and `iget` `--retries` .

Would it be possible to get this functionality into baton so that transitory failures can be retried?

**Comment by kjsanger** [comment]
That's possible if this API is exposed as part of iRODS C interface.

**Comment by kript** [comment]
I'm told it is, but can only spell C so can't confirm!

**Comment by kjsanger** [comment]
My reading of it at the moment is that since this will be done at `procApiRequest`, which is not called directly by baton, and that this will be configured in the environment file, I should need to do nothing in order for baton to adopt this behaviour. It's all happening in lower level API that baton doesn't touch directly.

**Comment by kjsanger** [comment]
Closed as inactive; the upstream issue in iRODS is still open.
